### PR TITLE
Update the README

### PR DESCRIPTION
**Pull request by mariyageorge01**
### What does this PR do?
This PR deals with updating the [Getting started](https://github.com/instructlab/website?tab=readme-ov-file#getting-started) section in the README.

The major aim of this PR is to remove the part where three package managers are listed.

> First, run the development server:
> 
> ```
> npm run dev
> # or
> yarn dev
> # or
> pnpm dev
> ```

### GitHub issue:
GitHub issue: Update the README https://github.com/instructlab/website/issues/178

FIXES: https://github.com/instructlab/website/issues/178

### CODE REVIEW

**Review by jjasghar — APPROVED** [review]
Awesome, thank you!

**Comment by joesepi** [comment]
I dont use Yarn. ¯\_(ツ)_/¯ 

I think its great to add more information on how to get started with the website, but I'm not sure what the rational is to remove the other package managers. If anything, it would be simpler to use npm since it comes with Node.js. :)

Can you simply add back the other package managers? You may also want to mention `npm install` as that will be necessary as well.

Thank you!!!!!

**Comment by mariyageorge01** [comment]
@joesepi 

> I dont use Yarn.

Interesting....

We do have a [yarn.lock](https://github.com/instructlab/website/blob/main/yarn.lock) file in this repository. Having a `yarn.lock` in the repo, made me think that we should be using `yarn`. Plus, the repo does not contain `package-lock.json` or `pnpm-lock.yaml`

> I think its great to add more information on how to get started with the website, but I'm not sure what the rational is to remove the other package managers. If anything, it would be simpler to use npm since it comes with Node.js. :)
> 
> Can you simply add back the other package managers? You may also want to mention npm install as that will be necessary as well.

I do agree that npm is simpler to use.

Do you want me to add back all the three package managers? Or just npm? (I personally don't think it is a wise choice to add multiple package managers)

**Comment by joesepi** [comment]
> We do have a [yarn.lock](https://github.com/instructlab/website/blob/main/yarn.lock) file in this repository. Having a `yarn.lock` in the repo, made me think that we should be using `yarn`. Plus, the repo does not contain `package-lock.json` or `pnpm-lock.yaml`

Thats a good catch. Let's just go with what you are suggesting: focus only on `yarn`

If you fix the linting errors, we can merge this PR.

Thanks!

**Comment by joesepi** [comment]
Ah, nevermind! I see you fixed the linting errors already!

**Review by joesepi — APPROVED** [review]

**Pull request merged**
