### PR TITLE
ci: add GitHub Action and Markdown linter

### PR DESCRIPTION
**Pull request by nathan-weinberg**
This is a meta-linter of sorts that lints GitHub Actions themselves

Should be useful when we introduce more CI to this repository

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
@mairin @connor-leech @jjasghar @sstano Hey y'all, I've added this GHA linter and fixed some linting issues but it did require changing the existing `nextjs` action - is there a way I can test if I broke any functionality or not? Last thing I want to do is set y'all back with this

**Review by russellb — APPROVED** [review]

**Comment by nathan-weinberg** [comment]
Will hold off on merging until I know I won't break the website deploys :smile:

**Review by joesepi — APPROVED** [review]
LGTM but I will check with @mscherer to plan to test it.

**Comment by nathan-weinberg** [comment]
@mscherer we can definitely hold this, no rush to do this before Summit

**Comment by nathan-weinberg** [comment]
@mscherer can we revisit this now that Summit is over?

**Comment by nathan-weinberg** [comment]
Rebased but I still need to harden these actions per @bjhargrave's examples in other repos

**Review by bjhargrave — CHANGES_REQUESTED** [review]
You also need to include `.github/dependabot.yml` to manage the actions.

See https://github.com/instructlab/.github/blob/main/.github/dependabot.yml

You should add a section to the dependabot config to handle the JS/yarn dependencies.

**Review by bjhargrave — APPROVED** [review]

**Pull request merged**
